language: node_js

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  apt:
    packages:
    - zsh

cache:
  directories:
  - node_modules
  - plugins
  - hooks
  - resources
  - typings
  - platforms

notifications:
  email:
    on_success: on_failure
